transcripts_path_train : "data/1_A_DLR_with_grapheme_Train.txt"
save_dir : 'results/DLR_2'
log_path : 'logs.txt'

tokenize_unit : 'grapheme'
architecture: 'hybrid'
loss_fn: 'hybrid'

ctc_rate : 0.1
learning_rate : 0.0001
epochs : 50
batch_size : 2
num_workers : 4
resume_epoch : -1

max_len : 200

use_video : True
raw_video : False

audio_transform_method : 'raw' 
audio_sample_rate : 14400
audio_n_channels : 2
audio_n_mels : None
audio_fram_length : None
audio_fram_shift : None
audio_normalize : True

video_n_channels : 3

spec_augment : False
freq_mask_para : None
freq_mask_num : None
time_mask_num : None

noise_augment : False
noise_path : None

encoder_n_layer : 12
encoder_d_model: 512
encoder_n_head: 8
encoder_ff_dim: 2048
encoder_dropout_p: 0.1

decoder_n_layer : 6
decoder_d_model: 512
decoder_n_head: 8
decoder_ff_dim: 2048
decoder_dropout_p: 0.1