transcripts_path_test : "data/pm_2_Train.txt"
vocab_label : 'avsr/vocabulary/kor_characters'
model_path : 'results/pm_2_0th/00001.pt'
save_dir : 'results/inference'
log_path : 'inference_results.txt'

batch_size : 4
num_workers : 4

use_video : True
raw_video : False

audio_transform_method : 'raw' 
audio_sample_rate : 14400
audio_n_channels : 2
audio_n_mels : None
audio_fram_length : None
audio_fram_shift : None
audio_normalize : True

video_n_channels : 3

encoder_n_layer : 6
encoder_d_model: 512
encoder_n_head: 8
encoder_ff_dim: 1024
encoder_dropout_p: 0.1

decoder_n_layer : 12
decoder_d_model: 512
decoder_n_head: 8
decoder_ff_dim: 1024
decoder_dropout_p: 0.1

max_len : 150