transcripts_path_test : "data/sample1.txt"
model_path : 'results/trained_model/tmp6/00099.pt'
log_path : 'inference_results6.txt'

num_workers : 4

tokenize_unit : 'character'
architecture: 'hybrid'
search_method : 'hybrid'
ctc_rate : 0.3

use_video : True
raw_video : False

audio_transform_method : 'raw' 
audio_sample_rate : 14400
audio_n_channels : 2
audio_n_mels : None
audio_fram_length : None
audio_fram_shift : None
audio_normalize : True

video_n_channels : 3

encoder_n_layer : 12
encoder_d_model: 512
encoder_n_head: 8
encoder_ff_dim: 2048
encoder_dropout_p: 0.1

decoder_n_layer : 6
decoder_d_model: 512
decoder_n_head: 8
decoder_ff_dim: 2048
decoder_dropout_p: 0.1

max_len : 20